### ISSUE TITLE
[meta] Suggestions to improve this project (tests, code formatting, conventions)

### ISSUE THREAD

**Issue by timbru31** [testingbot/testingbot-tunnel-launcher#4]
Hi,

I'd like to improve this project a bit.
Some information are IMO required and currently missing.
- What version of Node is the target? Do you plan to support v0.12 or even v0.10 too?
  - ES6 features like const, let, arrow functions, ... could be used
- What's the desired code formatting? (tabs vs spaces, indentation level, ...)
  - Maybe consider adding http://editorconfig.org/?
- How about ESLint? What ruleset should be extended/used?
- What's the policy of your dependencies? [caret vs tilde? fixed?](http://stackoverflow.com/a/22345808/1902598)
- What's with the devDependency `mocha`? Is it planned to add tests?
  - If yes, maybe add e.g. TravisCI?
- Are badges (like https://david-dm.org/, published npm version, test coverage, ...) welcomed?
- What's about [Commitizen](http://commitizen.github.io/cz-cli/) and [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog)?

Just some thoughts that I had, when I looked at this repository. 
I'm happy to assist with some of the points mentioned above if you are interested :)

**Comment by testingbot** [comment]
Hi @timbru31 

Thanks for the questions/suggestions!
- Currently we target the latest Node LTS release. ES6 features are welcome
- Agreed about editorconfig, we should use the same like we do on https://raw.githubusercontent.com/testingbot/wdio-testingbot-service/master/.editorconfig
- Regarding ESLint, we probably will also use the same https://raw.githubusercontent.com/testingbot/wdio-testingbot-service/master/.eslintrc
- For us, the caret policy seems to be preferable
- The `mocha` dependency was added to run tests in the future. However, we currently have only a couple of unit tests. We'll commit these. Indeed, TravisCI sounds look a good idea
- Badges are definitely welcome
- Have not checked Commitizen and conventional-changelog, looks interesting!

We welcome any help we get - there are indeed various things that can definitely be improved in this project

**Comment by timbru31** [comment]
Sound great :)

I've made a small todo/tasks list
- [x] Target latest Node LTS (#10)
- [x] Enhance code with "new" ES6 features (#10)
- [x] Add EditorConfig (https://github.com/testingbot/testingbot-tunnel-launcher/pull/5)
- [x] Add ESLint (#9)
- [x] Fix potential ESLint issues (#9)
- [x] Update dependencies with carets (#9)
- [x] Commit test files (@testingbot)
- [x] Add TravisCI
- [x] Add some awesome badges (#7) - more can be added if test coverage and CI build are enabled.
- [x] Add keywords section to package.json (#10)
- [x] Enable [Greenkeeper](https://greenkeeper.io/)

**Comment by timbru31** [comment]
@testingbot 
Now it's your turn to push your test files and enable TravisCI. Ping me if you need help :)

**Comment by testingbot** [comment]
Thanks for your contributions @timbru31  !
Need to polish the tests a bit - will push these asap
